### PR TITLE
Add 'attack' folder and components

### PR DESCRIPTION
**Pull request by kingthorin**
Part two of: zaproxy/zaproxy#5972

This commit includes advance updates in preparation for renaming of this repo.

Also see: https://github.com/zaproxy/zap-extensions/pull/2465

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
This addition PR contains a bunch more files than the removal PR because there was a bunch of help and build files to update.

**Comment by thc202** [comment]
I'd suggest updating the links now so that when the repo is renamed everything is as expected already.

**Comment by kingthorin** [comment]
Okay, will tackle that shortly

**Comment by kingthorin** [comment]
Done/added

**Comment by thc202** [comment]
Looks good, may I suggest update the attack files and backdoors to the latest from upstream?

**Comment by kingthorin** [comment]
Sure

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
